# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:shape_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the launch instance Shape config
      type Oci_Config::LaunchInstanceShapeConfigDetails = Struct[{
        Optional[ocpus]                         => Float,
        Optional[vcpus]                         => Integer,
        Optional[memory_in_gbs]                 => Float,
        Optional[processor_description]         => String[1],
        Optional[networking_bandwidth_in_gbps]  => Float,
        Optional[max_vnic_attachments]          => Integer,
        Optional[gpus]                          => Integer,
        Optional[gpu_description]               => String[1],
        Optional[local_disks]                   => Integer,
        Optional[local_disks_total_size_in_gbs] => Float,
        Optional[local_disk_description]        => String[1],
      }]
    ]
  DATA_TYPE
end
