# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:reset_period, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The reset period for the budget.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')

  defaultto('MONTHLY')
end
